services:
  backend:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - back-tier
    ports:
      - "5432:5432"
  frontend:
    build: .
    command: bash -c "bundle e rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/myapp
    networks:
      - front-tier
      - back-tier

networks:
  front-tier: {}
  back-tier: {}
